# version: 1
# formatters:
#   simple:
#     format: "%(asctime)s - %(levelname)s - %(message)s"

# handlers:
#   file_handler:
#     class: logging.FileHandler
#     formatter: simple
#     filename: /home/user1/Desktop/cypherQueryGeneration/logs/my_logfile.log

# loggers:
#   file_size_logger:
#     level: DEBUG
#     handlers: [file_handler]


version: 1
formatters:
  simple:
    format: "%(asctime)s - %(levelname)s - %(message)s"

handlers:
  file_handler:
    class: logging.FileHandler
    formatter: simple
    filename: /home/user1/Desktop/neo4jGraphDatabase/logs/my_logfile.log

root:
  level: DEBUG
  handlers: [file_handler]